# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dscc_pb2 as dscc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dscc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/dscc.LockService/Ping',
                request_serializer=dscc__pb2.PingRequest.SerializeToString,
                response_deserializer=dscc__pb2.PingResponse.FromString,
                _registered_method=True)
        self.AcquireGuard = channel.unary_unary(
                '/dscc.LockService/AcquireGuard',
                request_serializer=dscc__pb2.AcquireRequest.SerializeToString,
                response_deserializer=dscc__pb2.AcquireResponse.FromString,
                _registered_method=True)
        self.ReleaseGuard = channel.unary_unary(
                '/dscc.LockService/ReleaseGuard',
                request_serializer=dscc__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=dscc__pb2.ReleaseResponse.FromString,
                _registered_method=True)


class LockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireGuard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseGuard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=dscc__pb2.PingRequest.FromString,
                    response_serializer=dscc__pb2.PingResponse.SerializeToString,
            ),
            'AcquireGuard': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireGuard,
                    request_deserializer=dscc__pb2.AcquireRequest.FromString,
                    response_serializer=dscc__pb2.AcquireResponse.SerializeToString,
            ),
            'ReleaseGuard': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseGuard,
                    request_deserializer=dscc__pb2.ReleaseRequest.FromString,
                    response_serializer=dscc__pb2.ReleaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dscc.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dscc.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dscc.LockService/Ping',
            dscc__pb2.PingRequest.SerializeToString,
            dscc__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcquireGuard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dscc.LockService/AcquireGuard',
            dscc__pb2.AcquireRequest.SerializeToString,
            dscc__pb2.AcquireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseGuard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dscc.LockService/ReleaseGuard',
            dscc__pb2.ReleaseRequest.SerializeToString,
            dscc__pb2.ReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
