# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dscc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dscc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndscc.proto\x12\x04\x64scc\" \n\x0bPingRequest\x12\x11\n\tfrom_node\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x9b\x02\n\x0e\x41\x63quireRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\tembedding\x18\x02 \x03(\x02\x12\x14\n\x0cpayload_text\x18\x03 \x01(\t\x12\x13\n\x0bsource_file\x18\x04 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x05 \x01(\x03\x12:\n\x0eoperation_type\x18\x06 \x01(\x0e\x32\".dscc.AcquireRequest.OperationType\"b\n\rOperationType\x12\x1e\n\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14OPERATION_TYPE_WRITE\x10\x01\x12\x17\n\x13OPERATION_TYPE_READ\x10\x02\"\x99\x03\n\x0f\x41\x63quireResponse\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1f\n\x17server_received_unix_ms\x18\x03 \x01(\x03\x12\x1d\n\x15lock_acquired_unix_ms\x18\x04 \x01(\x03\x12%\n\x1dqdrant_write_complete_unix_ms\x18\x05 \x01(\x03\x12\x1d\n\x15lock_released_unix_ms\x18\x06 \x01(\x03\x12\x14\n\x0clock_wait_ms\x18\x07 \x01(\x03\x12!\n\x19\x62locking_similarity_score\x18\x08 \x01(\x02\x12\x19\n\x11\x62locking_agent_id\x18\t \x01(\t\x12\x17\n\x0fleader_redirect\x18\n \x01(\t\x12\x17\n\x0fserving_node_id\x18\x0b \x01(\t\x12\x15\n\rwait_position\x18\x0c \x01(\x05\x12\x12\n\nwake_count\x18\r \x01(\x05\x12\x12\n\nqueue_hops\x18\x0e \x01(\x05\x12\x19\n\x11\x61\x63tive_lock_count\x18\x0f \x01(\x05\"\"\n\x0eReleaseRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"\"\n\x0fReleaseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb6\x01\n\x0bLockService\x12-\n\x04Ping\x12\x11.dscc.PingRequest\x1a\x12.dscc.PingResponse\x12;\n\x0c\x41\x63quireGuard\x12\x14.dscc.AcquireRequest\x1a\x15.dscc.AcquireResponse\x12;\n\x0cReleaseGuard\x12\x14.dscc.ReleaseRequest\x1a\x15.dscc.ReleaseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dscc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=20
  _globals['_PINGREQUEST']._serialized_end=52
  _globals['_PINGRESPONSE']._serialized_start=54
  _globals['_PINGRESPONSE']._serialized_end=85
  _globals['_ACQUIREREQUEST']._serialized_start=88
  _globals['_ACQUIREREQUEST']._serialized_end=371
  _globals['_ACQUIREREQUEST_OPERATIONTYPE']._serialized_start=273
  _globals['_ACQUIREREQUEST_OPERATIONTYPE']._serialized_end=371
  _globals['_ACQUIRERESPONSE']._serialized_start=374
  _globals['_ACQUIRERESPONSE']._serialized_end=783
  _globals['_RELEASEREQUEST']._serialized_start=785
  _globals['_RELEASEREQUEST']._serialized_end=819
  _globals['_RELEASERESPONSE']._serialized_start=821
  _globals['_RELEASERESPONSE']._serialized_end=855
  _globals['_LOCKSERVICE']._serialized_start=858
  _globals['_LOCKSERVICE']._serialized_end=1040
# @@protoc_insertion_point(module_scope)
