// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dscc.proto

#include "dscc.pb.h"
#include "dscc.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace dscc {

static const char* LockService_method_names[] = {
  "/dscc.LockService/Ping",
  "/dscc.LockService/AcquireGuard",
  "/dscc.LockService/ReleaseGuard",
};

std::unique_ptr< LockService::Stub> LockService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LockService::Stub> stub(new LockService::Stub(channel, options));
  return stub;
}

LockService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Ping_(LockService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AcquireGuard_(LockService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReleaseGuard_(LockService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LockService::Stub::Ping(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::dscc::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dscc::PingRequest, ::dscc::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void LockService::Stub::async::Ping(::grpc::ClientContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dscc::PingRequest, ::dscc::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void LockService::Stub::async::Ping(::grpc::ClientContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dscc::PingResponse>* LockService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dscc::PingResponse, ::dscc::PingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dscc::PingResponse>* LockService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LockService::Stub::AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::dscc::AcquireResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dscc::AcquireRequest, ::dscc::AcquireResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AcquireGuard_, context, request, response);
}

void LockService::Stub::async::AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dscc::AcquireRequest, ::dscc::AcquireResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcquireGuard_, context, request, response, std::move(f));
}

void LockService::Stub::async::AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AcquireGuard_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dscc::AcquireResponse>* LockService::Stub::PrepareAsyncAcquireGuardRaw(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dscc::AcquireResponse, ::dscc::AcquireRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AcquireGuard_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dscc::AcquireResponse>* LockService::Stub::AsyncAcquireGuardRaw(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAcquireGuardRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LockService::Stub::ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::dscc::ReleaseResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dscc::ReleaseRequest, ::dscc::ReleaseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReleaseGuard_, context, request, response);
}

void LockService::Stub::async::ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dscc::ReleaseRequest, ::dscc::ReleaseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReleaseGuard_, context, request, response, std::move(f));
}

void LockService::Stub::async::ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReleaseGuard_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dscc::ReleaseResponse>* LockService::Stub::PrepareAsyncReleaseGuardRaw(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dscc::ReleaseResponse, ::dscc::ReleaseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReleaseGuard_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dscc::ReleaseResponse>* LockService::Stub::AsyncReleaseGuardRaw(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReleaseGuardRaw(context, request, cq);
  result->StartCall();
  return result;
}

LockService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LockService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LockService::Service, ::dscc::PingRequest, ::dscc::PingResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dscc::PingRequest* req,
             ::dscc::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LockService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LockService::Service, ::dscc::AcquireRequest, ::dscc::AcquireResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dscc::AcquireRequest* req,
             ::dscc::AcquireResponse* resp) {
               return service->AcquireGuard(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LockService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LockService::Service, ::dscc::ReleaseRequest, ::dscc::ReleaseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LockService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dscc::ReleaseRequest* req,
             ::dscc::ReleaseResponse* resp) {
               return service->ReleaseGuard(ctx, req, resp);
             }, this)));
}

LockService::Service::~Service() {
}

::grpc::Status LockService::Service::Ping(::grpc::ServerContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LockService::Service::AcquireGuard(::grpc::ServerContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LockService::Service::ReleaseGuard(::grpc::ServerContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace dscc

