// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dscc.proto
#ifndef GRPC_dscc_2eproto__INCLUDED
#define GRPC_dscc_2eproto__INCLUDED

#include "dscc.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace dscc {

class LockService final {
 public:
  static constexpr char const* service_full_name() {
    return "dscc.LockService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Ping(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::dscc::PingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::PingResponse>> AsyncPing(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::PingResponse>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::PingResponse>> PrepareAsyncPing(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::PingResponse>>(PrepareAsyncPingRaw(context, request, cq));
    }
    virtual ::grpc::Status AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::dscc::AcquireResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::AcquireResponse>> AsyncAcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::AcquireResponse>>(AsyncAcquireGuardRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::AcquireResponse>> PrepareAsyncAcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::AcquireResponse>>(PrepareAsyncAcquireGuardRaw(context, request, cq));
    }
    virtual ::grpc::Status ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::dscc::ReleaseResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::ReleaseResponse>> AsyncReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::ReleaseResponse>>(AsyncReleaseGuardRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::ReleaseResponse>> PrepareAsyncReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dscc::ReleaseResponse>>(PrepareAsyncReleaseGuardRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Ping(::grpc::ClientContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Ping(::grpc::ClientContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dscc::PingResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dscc::PingResponse>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dscc::AcquireResponse>* AsyncAcquireGuardRaw(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dscc::AcquireResponse>* PrepareAsyncAcquireGuardRaw(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dscc::ReleaseResponse>* AsyncReleaseGuardRaw(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dscc::ReleaseResponse>* PrepareAsyncReleaseGuardRaw(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Ping(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::dscc::PingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::PingResponse>> AsyncPing(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::PingResponse>>(AsyncPingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::PingResponse>> PrepareAsyncPing(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::PingResponse>>(PrepareAsyncPingRaw(context, request, cq));
    }
    ::grpc::Status AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::dscc::AcquireResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::AcquireResponse>> AsyncAcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::AcquireResponse>>(AsyncAcquireGuardRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::AcquireResponse>> PrepareAsyncAcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::AcquireResponse>>(PrepareAsyncAcquireGuardRaw(context, request, cq));
    }
    ::grpc::Status ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::dscc::ReleaseResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::ReleaseResponse>> AsyncReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::ReleaseResponse>>(AsyncReleaseGuardRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::ReleaseResponse>> PrepareAsyncReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dscc::ReleaseResponse>>(PrepareAsyncReleaseGuardRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Ping(::grpc::ClientContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response, std::function<void(::grpc::Status)>) override;
      void Ping(::grpc::ClientContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response, std::function<void(::grpc::Status)>) override;
      void AcquireGuard(::grpc::ClientContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response, std::function<void(::grpc::Status)>) override;
      void ReleaseGuard(::grpc::ClientContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::dscc::PingResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dscc::PingResponse>* PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::dscc::PingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dscc::AcquireResponse>* AsyncAcquireGuardRaw(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dscc::AcquireResponse>* PrepareAsyncAcquireGuardRaw(::grpc::ClientContext* context, const ::dscc::AcquireRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dscc::ReleaseResponse>* AsyncReleaseGuardRaw(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dscc::ReleaseResponse>* PrepareAsyncReleaseGuardRaw(::grpc::ClientContext* context, const ::dscc::ReleaseRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Ping_;
    const ::grpc::internal::RpcMethod rpcmethod_AcquireGuard_;
    const ::grpc::internal::RpcMethod rpcmethod_ReleaseGuard_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Ping(::grpc::ServerContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response);
    virtual ::grpc::Status AcquireGuard(::grpc::ServerContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response);
    virtual ::grpc::Status ReleaseGuard(::grpc::ServerContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Ping() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::dscc::PingRequest* /*request*/, ::dscc::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::dscc::PingRequest* request, ::grpc::ServerAsyncResponseWriter< ::dscc::PingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AcquireGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AcquireGuard() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AcquireGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcquireGuard(::grpc::ServerContext* /*context*/, const ::dscc::AcquireRequest* /*request*/, ::dscc::AcquireResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAcquireGuard(::grpc::ServerContext* context, ::dscc::AcquireRequest* request, ::grpc::ServerAsyncResponseWriter< ::dscc::AcquireResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReleaseGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReleaseGuard() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ReleaseGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseGuard(::grpc::ServerContext* /*context*/, const ::dscc::ReleaseRequest* /*request*/, ::dscc::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReleaseGuard(::grpc::ServerContext* context, ::dscc::ReleaseRequest* request, ::grpc::ServerAsyncResponseWriter< ::dscc::ReleaseResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Ping<WithAsyncMethod_AcquireGuard<WithAsyncMethod_ReleaseGuard<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::dscc::PingRequest, ::dscc::PingResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dscc::PingRequest* request, ::dscc::PingResponse* response) { return this->Ping(context, request, response); }));}
    void SetMessageAllocatorFor_Ping(
        ::grpc::MessageAllocator< ::dscc::PingRequest, ::dscc::PingResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dscc::PingRequest, ::dscc::PingResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::dscc::PingRequest* /*request*/, ::dscc::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::dscc::PingRequest* /*request*/, ::dscc::PingResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AcquireGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AcquireGuard() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::dscc::AcquireRequest, ::dscc::AcquireResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dscc::AcquireRequest* request, ::dscc::AcquireResponse* response) { return this->AcquireGuard(context, request, response); }));}
    void SetMessageAllocatorFor_AcquireGuard(
        ::grpc::MessageAllocator< ::dscc::AcquireRequest, ::dscc::AcquireResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dscc::AcquireRequest, ::dscc::AcquireResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AcquireGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcquireGuard(::grpc::ServerContext* /*context*/, const ::dscc::AcquireRequest* /*request*/, ::dscc::AcquireResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AcquireGuard(
      ::grpc::CallbackServerContext* /*context*/, const ::dscc::AcquireRequest* /*request*/, ::dscc::AcquireResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReleaseGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReleaseGuard() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::dscc::ReleaseRequest, ::dscc::ReleaseResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dscc::ReleaseRequest* request, ::dscc::ReleaseResponse* response) { return this->ReleaseGuard(context, request, response); }));}
    void SetMessageAllocatorFor_ReleaseGuard(
        ::grpc::MessageAllocator< ::dscc::ReleaseRequest, ::dscc::ReleaseResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dscc::ReleaseRequest, ::dscc::ReleaseResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReleaseGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseGuard(::grpc::ServerContext* /*context*/, const ::dscc::ReleaseRequest* /*request*/, ::dscc::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReleaseGuard(
      ::grpc::CallbackServerContext* /*context*/, const ::dscc::ReleaseRequest* /*request*/, ::dscc::ReleaseResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Ping<WithCallbackMethod_AcquireGuard<WithCallbackMethod_ReleaseGuard<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Ping() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::dscc::PingRequest* /*request*/, ::dscc::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AcquireGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AcquireGuard() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AcquireGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcquireGuard(::grpc::ServerContext* /*context*/, const ::dscc::AcquireRequest* /*request*/, ::dscc::AcquireResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReleaseGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReleaseGuard() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ReleaseGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseGuard(::grpc::ServerContext* /*context*/, const ::dscc::ReleaseRequest* /*request*/, ::dscc::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Ping() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::dscc::PingRequest* /*request*/, ::dscc::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AcquireGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AcquireGuard() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AcquireGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcquireGuard(::grpc::ServerContext* /*context*/, const ::dscc::AcquireRequest* /*request*/, ::dscc::AcquireResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAcquireGuard(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReleaseGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReleaseGuard() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ReleaseGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseGuard(::grpc::ServerContext* /*context*/, const ::dscc::ReleaseRequest* /*request*/, ::dscc::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReleaseGuard(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Ping() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Ping(context, request, response); }));
    }
    ~WithRawCallbackMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::dscc::PingRequest* /*request*/, ::dscc::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ping(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AcquireGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AcquireGuard() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AcquireGuard(context, request, response); }));
    }
    ~WithRawCallbackMethod_AcquireGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AcquireGuard(::grpc::ServerContext* /*context*/, const ::dscc::AcquireRequest* /*request*/, ::dscc::AcquireResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AcquireGuard(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReleaseGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReleaseGuard() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReleaseGuard(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReleaseGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReleaseGuard(::grpc::ServerContext* /*context*/, const ::dscc::ReleaseRequest* /*request*/, ::dscc::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReleaseGuard(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Ping : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Ping() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dscc::PingRequest, ::dscc::PingResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dscc::PingRequest, ::dscc::PingResponse>* streamer) {
                       return this->StreamedPing(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Ping() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Ping(::grpc::ServerContext* /*context*/, const ::dscc::PingRequest* /*request*/, ::dscc::PingResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPing(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dscc::PingRequest,::dscc::PingResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AcquireGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AcquireGuard() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dscc::AcquireRequest, ::dscc::AcquireResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dscc::AcquireRequest, ::dscc::AcquireResponse>* streamer) {
                       return this->StreamedAcquireGuard(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AcquireGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AcquireGuard(::grpc::ServerContext* /*context*/, const ::dscc::AcquireRequest* /*request*/, ::dscc::AcquireResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAcquireGuard(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dscc::AcquireRequest,::dscc::AcquireResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReleaseGuard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReleaseGuard() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dscc::ReleaseRequest, ::dscc::ReleaseResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dscc::ReleaseRequest, ::dscc::ReleaseResponse>* streamer) {
                       return this->StreamedReleaseGuard(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReleaseGuard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReleaseGuard(::grpc::ServerContext* /*context*/, const ::dscc::ReleaseRequest* /*request*/, ::dscc::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReleaseGuard(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dscc::ReleaseRequest,::dscc::ReleaseResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Ping<WithStreamedUnaryMethod_AcquireGuard<WithStreamedUnaryMethod_ReleaseGuard<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Ping<WithStreamedUnaryMethod_AcquireGuard<WithStreamedUnaryMethod_ReleaseGuard<Service > > > StreamedService;
};

}  // namespace dscc


#endif  // GRPC_dscc_2eproto__INCLUDED
